apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensw
spec:
  selector:
    matchLabels:
      app: opensw-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: opensw-deployment
    spec:
      containers:
      - name: opensw-deployment
        image: blueccc/opensw_9
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: redmine
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DB
          value: redmine
        ports:
        - containerPort: 3000
      nodeName: k8s-node1
