# redmine-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:latest
        env:
          - name: REDMINE_DB_MYSQL
            value: mysql
          - name: REDMINE_DB_DATABASE
            value: redmine
          - name: REDMINE_DB_USERNAME
            value: redmine
          - name: REDMINE_DB_PASSWORD
            value: password
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-data
          mountPath: /usr/src/redmine/files
      volumes:
      - name: redmine-data
      nodeName: k8s-node3
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  selector:
    app: redmine
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

# persistent-volume.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/mysql-data"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/redmine-data"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
